services:
  postgres:
    image: postgres:16
    container_name: bms_postgres
    environment:
      POSTGRES_USER: purvisonthalia
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: bms
    ports:
      - "5433:5432"
    volumes:
      - bms_postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  bms_postgres_data: